- block:
    - name: read instance data
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack server list -f json --name {{ inventory_hostname_short }}
      register: instance_data
      failed_when: instance_data.stdout == ""
      changed_when: false

    - debug: var=(instance_data.stdout|from_json)[0]["Networks"]|regex_replace('internal_'+osp_tenant+'=\d+\.\d+\.\d+\.\d+,?\s*','')

    - name: create floating IP
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack ip floating create {{ infrastructure_network_guests.netname }} -f json
      register: floating_ip
      when: ( instance_data.stdout | from_json )[0]['Networks'] | regex_replace('internal_' + osp_tenant + "=\d+\.\d+\.\d+\.\d+,?\s*",'') == ""

    - name: associate floating IP
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack ip floating add {{ floating_ip.stdout | from_json | selectattr("Field","equalto","ip") | map(attribute="Value") | join(" ") }} {{ inventory_hostname_short }}
      when: ( instance_data.stdout | from_json )[0]["Networks"] | regex_replace('internal_' + osp_tenant + "=\d+\.\d+\.\d+\.\d+,?\s*",'') == ""

  become: yes
  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  delegate_to: rhosp-director
