- block:
    - include: configure_additional_ip_addresses.yml
    - include: register_libvirt_hook.yml
    - include: create_iptables_config.yml
  when: mode=="create" and external_network_config.services_network_dnat is defined

- block:
    - name: destroy networks (to remove IPTables entries)
      shell: virsh net-destroy {{ item.netname }}
      with_items: "{{ infrastructure_networks }}"
    - name: remove iptables config
      file: path=/etc/hailstorm_iptables.xml state=absent
    - include: remove_libvirt_hook.yml
    - name: start networks
      shell: virsh net-start {{ item.netname }}
      with_items: "{{ infrastructure_networks }}"
      ignore_errors: true
      # may throw an error since restarting libvirtd also restarts the network it seems
    - include: remove_additional_ip_addresses.yml
  when: mode=="destroy" and external_network_config.services_network_dnat is defined
