---
mem: 2048
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

repos:
  - rhel-7-server-rpms
packages: bind,dovecot,postfix
activation_key: AK-CV-OS-RHEL7-SERVER-PROD
pool_regex: "{{ rhel_subscription_pool_regex }}"

catch_all_user: catchall

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - SMTP:
   port: 25
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - IMAP:
   port: 143
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
 - IMAPSSL:
   port: 993
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true
