---
mem: "{{ layer2_rhev_manager_mem }}"
vcpu: "{{ layer2_rhev_manager_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  partition_table:
    lvmpv: 59500
    swap: 16384
    home: 2048
    root: 20000

pool_regex: "{{ rhev_subscription_pool_regex }}"

repos: "{{ rhevm_repos }}"
packages: rhevm,ovirt-engine-extension-aaa-ldap-setup,rhevm-dwh

ksdevice: eth1

tdagent_configs:
  - tag: syslog.messages
    path: /var/log/messages
    pos_file: /var/log/td-agent/messages_log.pos
    format: syslog
    permissions:
      - path: /var/log/messages
        mode: o+r
  - tag: engine.log
    path: /var/log/ovirt-engine/engine.log
    pos_file: /var/log/td-agent/ovirt_engine_log.pos
    format: /^(?<time>[^ ]* [^ ]*) (?<loglevel>[^ ]*) +\[(?<component>[^ ]*)\] +\((?<thread>[^ ]*)\) +(?<message>.*)$/
    time_format: "%Y-%m-%d %H:%M:%S,%L"
    permissions:
      - path: /var/log/ovirt-engine
        mode: o+xr
      - path: /var/log/ovirt-engine/engine.log
        mode: o+r
