---
mem: "{{ layer2_rhosp_director_mem }}"
vcpu: "{{ layer2_rhosp_director_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  # partition_table:
  #   lvmpv: 59500
  #   swap: 4096
  #   home: 2048
  #   root: 50000
  physvols:
    boot: 500
    rhel: 59500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 4096
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 50000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048


nic_attachments:
  - "{{ infrastructure_network_rhosp_provisioning }}"
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
default_route_via: "{{ infrastructure_network_services }}"
name_service_via: "{{ infrastructure_network_services }}"

pool_regex: "{{ rhosp_subscription_pool_regex }}"
repos: "{{ rhosp_undercloud_repos }}"

packages: python-rdomanager-oscplugin,python-dracclient,rhosp-director-images,rhosp-director-images-ipa
disable_services:
  - NetworkManager

image_path: /home/stack/images

ironic_rpc_timeout: 600
nova_rpc_timeout: 600

# will be populated during runtime
os_auth: {}
