- name: get all host collections
  shell: hammer host-collection list --organization "Default Organization" | awk '{ print $3 }'
  register: host_collections
  changed_when: false

# just fill the list with the host collections that are needed
- name: create host collections
  command: hammer host-collection create --organization "Default Organization" --name {{ item }}
  when: "item not in host_collections.stdout"
  with_items: "{{ content_config | map(attribute='host_collection') | list | unique }}"
