# prepare  exports
- name: create storage domain directory
  file: state=directory path={{ item.path }} mode="{{ file_mode }}" owner="{{ owner }}" group="{{ group }}"
  with_items: "{{ items }}"
- name: create /etc/exports entry
  lineinfile: dest=/etc/exports regexp="{{ item.path }}.*" line="{{ item.path }} {{ infrastructure_network_storage.default_gw_host_prefix }}{{ export_params }}"
  register: etc_exports
  with_items: "{{ items }}"
- name: export file systems
  command: exportfs -a
  when: etc_exports|changed
