- block:
    - name: create ose providers
      shell: curl -k -u admin:{{ root_password }} -XPOST -d'{{ lookup('template', 'ose_provider.json.j2') | to_json }}' https://{{ vm_nics[0].ip }}/api/providers
      register: ose_provider
    - debug: var=ose_provider
  when: mode=="create"
