mem: "{{ layer2_rhev_hypervisor_mem }}"
vcpu: "{{ layer2_rhev_hypervisor_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000

repos: "{{ rhevh_repos }}"
pool_regex: "{{ rhev_subscription_pool_regex }}"

packages: iptables-services
ntp_client: ntpd

disable_services:
  - firewalld

nic_attachments:
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_storage }}"
  - "{{ infrastructure_network_guests }}"
  - "{{ infrastructure_network_rhosp_provisioning }}"
default_route_via: "{{ infrastructure_network_services }}"
name_service_via: "{{ infrastructure_network_services }}"
