- block:
    - name: get image list (default project)
      shell: >
        . ~/overcloudrc_v3 &&
        openstack image list -f json
      register: images
      changed_when: false

    # - name: load CirrOS image (default project)
    #   shell: >
    #     . ~/overcloudrc_v3 &&
    #     curl http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img |
    #     openstack image create --public --disk-format qcow2 CirrOS
    #   when: '"CirrOS" not in images.stdout_lines'

    - name: load uncompressed KVM images (from layer1 host binary dir)
      shell: >
        . ~/overcloudrc_v3 &&
        ssh -o StrictHostKeyChecking=no {{ rhosp_stack_user }}@{{ infrastructure_network_admin.default_gw_host_prefix | ipaddr('address') }} cat {{ layer1_binary_dir }}/{{ item.image }} |
        openstack image create --public --disk-format qcow2 {{ item.name }}
      when: item.name not in images.stdout | from_json | map(attribute="Name") | list and not item.image | search('\.gz$')
      with_items: "{{ osp_kvm_images }}"

    - name: load compressed KVM images (from layer1 host binary dir)
      shell: >
        . ~/overcloudrc_v3 &&
        ssh -o StrictHostKeyChecking=no {{ rhosp_stack_user }}@{{ infrastructure_network_admin.default_gw_host_prefix | ipaddr('address') }} zcat {{ layer1_binary_dir }}/{{ item.image }} |
        openstack image create --public --disk-format qcow2 "{{ item.name }}"
      when: item.name not in images.stdout | from_json | map(attribute="Name") | list and item.image | search('\.gz$')
      with_items: "{{ osp_kvm_images }}"
  become: yes
  become_user: "{{ rhosp_stack_user }}"
