- block:
    - include: register_overcloud_nodes.yml
      tags: ['register']
    - include: create_overcloud.yml
      tags: ['overcloud-deploy']
      vars:
        templates:
          - network-isolation-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - extra-config-post-deployment-all.sh
          - ceilometer-config-environment.yaml
          - storage-environment.yaml
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - rhel-registration-environment.yaml
          - timezone-environment.yaml
    - include: adapt_to_keystone_v3.yml
      tags: ['overcloud-config-keystone']
    - include: configure_tenants.yml
      tags: ['overcloud-config-tenants']
    - include: configure_user_access.yml
      tags: ['overcloud-config-users']
    - include: configure_neutron.yml
      tags: ['overcloud-config-neutron']
    - include: configure_security.yml
      tags: ['overcloud-config-security']
    - include: configure_images.yml
      tags: ['overcloud-config-images']
  when: mode=="create"

- block:
    - include: destroy_overcloud.yml
      tags: ['overcloud-deploy']
    - include: unregister_overcloud_nodes.yml
      tags: ['register']
  when: mode=="destroy"

- block:
    - include: scale_down_via_hostname.yml
      vars:
        templates:
          - network-isolation-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - ceilometer-config-environment.yaml
          - storage-environment.yaml
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - rhel-registration-environment.yaml
          - timezone-environment.yaml
  when: mode=="reset"
