- block:
    - include: register_overcloud_nodes.yml
      tags: ['register']
    - include: create_overcloud.yml
      tags: ['overcloud-deploy']
    - include: read_overcloudrc_into_facts.yml
    - include: configure_tenants.yml
      tags: ['overcloud-config-tenants']
    - include: configure_user_access.yml
      tags: ['overcloud-config-users']
    - include: configure_neutron.yml
      tags: ['overcloud-config-neutron']
    - include: configure_security.yml
      tags: ['overcloud-config']
    - include: configure_images.yml
      tags: ['overcloud-config']
  when: mode=="create"

- block:
    - include: destroy_overcloud.yml
      tags: ['overcloud-deploy']
    - include: unregister_overcloud_nodes.yml
      tags: ['register']
  when: mode=="destroy"
