layer1_ansible_host: storm2.coe.muc.redhat.com
hailstorm_dns_domain: hailstorm2.coe.muc.redhat.com

disable_registration_against_satellite: true

# if this attribute is present, the binaries (except for the SSH keys)
# will be copied from the layer1 host instead of the control host
# you need to ensure they are there before running the playbook
layer1_binary_dir: /var/hailstorm/binary
layer1_qcow_storage:
  poolname: 'sata'
  path: /var/hailstorm/images

nfs_kickstart_folder: /var/hailstorm/kickstart
nfs_rhev_data_domain_path: /var/hailstorm/rhev-data1
nfs_rhev_iso_domain_path: /var/hailstorm/rhev-iso1
nfs_rhev_export_domain_path: /var/hailstorm/rhev-export1

nfs_ose3_pv_path: /var/hailstorm/ose3-pv

layer2_rhev_manager_mem: 16384
layer2_rhev_manager_cpu: 4
layer2_rhev_hypervisor_mem: 32768
layer2_rhev_hypervisor_cpu: 8

layer2_rhosp_director_mem: 16384
layer2_rhosp_director_cpu: 4
layer2_rhosp_control_mem: 8192
layer2_rhosp_control_cpu: 4
layer2_rhosp_compute_mem: 32768
layer2_rhosp_compute_cpu: 8

layer2_satellite_mem: 16384
layer2_satellite_cpu: 4

layer2_ose3node_mem: 16384
layer2_ose3node_cpu: 8
layer2_ose3master_mem: 4096
layer2_ose3master_cpu: 4

# if a property http_proxy is defined, satellite will be configured to sync via http_proxy
http_proxy:
  proxyname: proxy.coe.muc.redhat.com
  port: 3128
  protocol: https


dnat_rules:
  layer1_dev: em1
  mapping:
    - expose_machine: satellite
      on_host_prefix: 10.32.105.20/32
      ports:
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
        - from_port: 22
          to_port: 22
          proto: tcp
    - expose_machine: ipa
      on_host_prefix: 10.32.105.21/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
    - expose_machine: infrastructure
      on_host_prefix: 10.32.105.22/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 53
          to_port: 53
          proto: tcp
        - from_port: 53
          to_port: 53
          proto: udp
        - from_port: 143
          to_port: 143
          proto: tcp
        - from_port: 993
          to_port: 993
          proto: tcp
        - from_port: 25
          to_port: 25
          proto: tcp
        - from_port: 465
          to_port: 465
          proto: tcp
    - expose_machine: rhevm
      on_host_prefix: 10.32.105.23/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
    - expose_machine: cloudforms
      on_host_prefix: 10.32.105.24/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
    - expose_machine: ose3-lb
      on_host_prefix: 10.32.105.25/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 443
          to_port: 8443
          proto: tcp
        - from_port: 8443
          to_port: 8443
          proto: tcp
    - expose_machine: ose3-infranode1
      on_host_prefix: 10.32.105.26/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
    - expose_machine: efk
      on_host_prefix: 10.32.105.27/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
    - expose_machine: rhosp-director
      on_host_prefix: 10.32.105.28/32
      ports:
        - from_port: 22
          to_port: 22
          proto: tcp
    - expose_machine: openstack
      on_host_prefix: 10.32.105.29/32
      ports:
        - from_port: 80
          to_port: 80
          proto: tcp
        - from_port: 443
          to_port: 443
          proto: tcp
