# prepare  exports
- name: create storage domain directory
  file: state=directory path={{ nfs_ose3_pv_path }} mode=0755 owner=nfsnobody group=nfsnobody
- name: create pv subdirectories
  file: state=directory path={{ nfs_ose3_pv_path }}/{{ item }} mode=0777 owner=nfsnobody group=nfsnobody
  with_sequence: start=0 end=20 format=pv%02d
- name: create /etc/exports entry
  lineinfile: dest=/etc/exports line="{{ nfs_ose3_pv_path }}/{{ item }} {{ infrastructure_network_storage.default_gw_host_prefix }}(rw,root_squash,no_wdelay)"
  register: etc_exports
  with_sequence: start=0 end=20 format=pv%02d
- name: export file systems
  command: exportfs -a
  when: etc_exports|changed
