- block:
    - block:
        - name: retrieve undercloud admin password
          command: hiera admin_password
          register: undercloud_password
          failed_when: undercloud_password.stdout == ""
          changed_when: false
        - name: retrieve overcloud admin password
          command: awk -F = '/OS_PASSWORD/{ print $2 }' ~stack/overcloudrc
          register: overcloud_password
          failed_when: overcloud_password.stdout == ""
          changed_when: false
        - name: retrieve overcloud amqp username/password
          command: awk -F \" '/default_/{ print $2 }' /etc/rabbitmq/rabbitmq.config
          register: undercloud_amqp_usernamepw
          failed_when: undercloud_amqp_usernamepw.stdout == ""
          changed_when: false
        - name: retrieve stack user private key (and remove delimiter and newlines)
          shell: awk '!/---/{ printf "%s",$0 }' ~stack/.ssh/id_rsa
          register: stack_user_priv_key
          failed_when: stack_user_priv_key.stdout == ""
          changed_when: false
      delegate_to: rhosp-director
    - name: create osp provider
      shell: curl -k -u admin:{{ root_password }} -XPOST -d'{{ lookup('template', 'osp_provider.json.j2') | to_json }}' https://{{ vm_nics[0].ip }}/api/v2.1.0/providers
      register: osp_provider
      with_items:
        - type: "ManageIQ::Providers::Openstack::CloudManager"
          name: "RHOSP Overcloud"
          ip: "192.168.101.173"
          admin_password: "{{ overcloud_password.stdout }}"
        - type: "ManageIQ::Providers::Openstack::InfraManager"
          name: "rhosp-director"
          ip: "192.168.105.30"
          admin_password: "{{ undercloud_password.stdout }}"
          metrics_username: "{{ undercloud_amqp_usernamepw.stdout_lines[0] }}"
          metrics_password: "{{ undercloud_amqp_usernamepw.stdout_lines[1] }}"
          ssh_priv_key: "{{ stack_user_priv_key.stdout }}"
    - debug: var=osp_provider
  when: mode=="create"
