- name: create temp dir locally
  local_action: command mktemp -d
  register: mktemp
- name: download CloudForms rake scripts
  local_action: shell cd {{ mktemp.stdout }} && git clone https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git
- name: upload scripts zip file to CF
  copy: src={{ mktemp.stdout }}/cfme-rhconsulting-scripts dest=/tmp/ mode=0644
- name: remove temp dir locally
  local_action: file name={{ mktemp.stdout }} state=absent
- name: expand and install scripts
  shell: cd /tmp/cfme-rhconsulting-scripts && make install
- name: remove temp dir on cfme
  file: name=/tmp/cfme-rhconsulting-scripts state=absent
