---
# - hosts: all
#   remote_user: root
#   gather_facts: false
#   tasks:
#     - set_fact:
#         rhsm_username: "{{ rhsm_username }}"
#         rhsm_password: "{{ rhsm_password }}"
#       tags:
#         - always
#     - debug: var=vm_nics
#       tags:
#         - always
#     # - debug: msg={{ vm_nics }}
#     #   tags:
#     #     - always
#
#   vars_prompt:
#     - name: "rhsm_username"
#       prompt: "what is your Red Hat Subscription Manager username?"
#       default: "wrichter"
#       private: no
#     - name: "rhsm_password"
#       prompt: "what is your Red Hat Subscription Manager password?"

#### OPENSTACK ####

- hosts: layer1
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer1', 'rhosp' ]
  roles:
    - role: layer1_rhosp
      tags: [ 'rhosp', layer1 ]
      mode: create

- hosts: rhosp-all
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhel, tags: [ 'layer2', 'rhosp', 'rhel'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'rhosp', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhosp_director, tags: ['layer2', 'rhosp', 'undercloud' ], mode: create }
    - { role: layer2_rhosp_overcloud, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }

# - hosts: lookbusy-osp
#   remote_user: root
#   gather_facts: false
#   roles:
#     - { role: layer3_vm_on_openstack, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'vm'], mode: create }
#     - { role: layer2_rhel, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'rhel'], mode: create }
#     - { role: layer3_lookbusy, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp' ], mode: create }
