---
# - hosts: all
#   remote_user: root
#   gather_facts: false
#   tasks:
#     - set_fact:
#         rhsm_username: "{{ rhsm_username }}"
#         rhsm_password: "{{ rhsm_password }}"
#       tags:
#         - always
#     - debug: var=vm_nics
#       tags:
#         - always
#     # - debug: msg={{ vm_nics }}
#     #   tags:
#     #     - always
#
#   vars_prompt:
#     - name: "rhsm_username"
#       prompt: "what is your Red Hat Subscription Manager username?"
#       default: "wrichter"
#       private: no
#     - name: "rhsm_password"
#       prompt: "what is your Red Hat Subscription Manager password?"


#### CLOUDFORMS ####

- hosts: cloudforms
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_cloudforms_rhev, tags: [ 'layer3', 'cf' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer3', 'cf', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer3_cloudforms_config, tags: [ 'layer3', 'cf', 'cfme-config' ], mode: create }
# RHEL after cloudforms config, to ensure the hostname is set before subscribing
    - { role: layer2_rhel, tags: [ 'layer3', 'cf', 'rhel'], mode: create }
    - { role: layer3_cloudforms_osp, tags: [ 'layer3', 'cf', 'cfme-osp-provider' ], mode: create }

- hosts: ose3-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_cfme_enablement, tags: [layer2, 'cf', 'ose3', 'cfme-ose3-provider'], mode: create }

- hosts: cloudforms
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_cloudforms_openshift, tags: [ 'layer3', 'cf', 'cfme-ose3-provider' ], mode: create }
#    - { role: layer3_cloudforms_content, tags: [ 'layer3', 'cf', 'cfme-content' ], mode: create, content_location: "../CloudForms-Internals" }

#### EFK ####

- hosts: efk
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'efk', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'efk', 'rhel'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'efk', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_efk_rhosp_optools, tags: [ 'layer2', 'efk', 'efk-install'], mode: create }
