---
- hosts: dev-client
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','dev-client', 'ose3', 'vm' ]
      mode: start
    - role: layerX_openshift_demo_redhatmsa_on_devclient
      tags: [ 'layer2','dev-client', 'ose3', 'msademo' ]
      mode: destroy
    - role: layerX_ipa_client
      tags: [ 'layer2','dev-client', 'ose3', 'ipa-client' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','dev-client', 'ose3', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','dev-client', 'ose3', 'vm' ]
      mode: destroy

- hosts: lookbusy-rhev
  gather_facts: false
  remote_user: root
  roles:
    - role: layer3_vm_on_rhev
      tags: [ 'layer3','lookbusy-rhev','lookbusy' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer3','lookbusy-rhev','lookbusy', 'rhel' ]
      mode: destroy
    - role: layer3_vm_on_rhev
      tags: [ 'layer3','lookbusy-rhev','lookbusy', 'vm' ]
      mode: destroy

- hosts: lookbusy-osp
  gather_facts: false
  remote_user: root
  roles:
    - role: layer3_vm_on_openstack
      tags: [ 'layer3','lookbusy-osp','lookbusy' ]
      mode: readfacts
    - role: layer2_rhel
      tags: [ 'layer3','lookbusy-osp','lookbusy', 'rhel' ]
      mode: destroy
    - role: layer3_vm_on_openstack
      tags: [ 'layer3','lookbusy-osp','lookbusy', 'vm' ]
      mode: destroy

- hosts: efk
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','efk', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','efk', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','efk', 'vm' ]
      mode: destroy

- hosts: ose3-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_demo_monster, tags: ['ose3-demo','ose3-content'], mode: destroy }
    - { role: layerX_openshift_devops_tools, tags: ['ose3-devops','ose3-content'], mode: destroy }
    - { role: layerX_openshift_installer, tags: ['ose3-metrics', 'ose3-roles','ose3-content'], mode: destroy }

- hosts: ose3
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','ose3', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','ose3', 'rhel' ]
      mode: destroy

# - hosts: ose3-installer
#   gather_facts: false
#   remote_user: root
#   roles:
#     - role: layerX_openshift_installer
#       tags: [ 'layer2','ose3', 'ose3-metrics' ]
#       mode: destroy

- hosts: ose3
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','ose3', 'vm' ]
      mode: destroy

- hosts: cloudforms
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_rhel
      tags: [ 'layer3', 'cf', 'rhel']
      mode: destroy
    - role: layer3_cloudforms_rhev
      tags: [ 'layer3', 'cf' ]
      mode: destroy

- hosts: rhevm
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_tdagent, tags: [ 'layer2', 'rhev', 'tdagent' ], mode: destroy }
    - role: layer2_rhevm_ldap
      tags: [ 'rhevm-ldap','rhev' ]
      mode: destroy

- hosts: rhev
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhev', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','rhev', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','rhev', 'vm' ]
      mode: destroy

- hosts: rhosp-director
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhosp', 'rhel' ]
      mode: start
    - role: layer2_rhosp_overcloud
      tags: [ 'layer2', 'rhosp', 'overcloud' ]
      mode: destroy
    - role: layer2_rhosp_director
      tags: [ 'layer2', 'rhosp', 'undercloud' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','rhosp', 'rhel'  ]
      mode: destroy

- hosts: rhosp-all
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhosp', 'vm' ]
      mode: destroy

- hosts: ipa
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','ipa', 'rhel' ]
      mode: start
    - role: layer2_ipa
      tags: [ 'layer2', 'ipa' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','ipa', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','ipa', 'vm' ]
      mode: destroy


- hosts: infrastructure
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','infrastructure', 'vm' ]
      mode: start
    - role: layer2_infrastructure
      tags: [ 'layer2', 'infrastructure' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','infrastructure', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','infrastructure', 'vm' ]
      mode: destroy


- hosts: test-rhel
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2',  "test-rhel", 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2', 'rhel', 'test-rhel'  ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2', 'vm', 'test-rhel' ]
      mode: destroy


# - hosts: satellite
#   gather_facts: false
#   remote_user: root
#   roles:
#     - role: layer2_vms
#       tags: [ 'layer2','satellite', 'rhel' ]
#       mode: start
#     - role: layer2_vms
#       tags: [ 'layer2','satellite', 'rhel' ]
#       mode: start
#     - role: layer2_rhel
#       tags: [ 'layer2','satellite', 'rhel'  ]
#       mode: destroy
#     - role: layer2_vms
#       tags: [ 'layer2','satellite', 'vm' ]
#       mode: destroy

- hosts: layer1
  gather_facts: false
  remote_user: root
  roles:
    # - role: layer1_vms
    #   tags: [ 'rhev', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: rhev
    - role: layer1_openshift
      tags: [ 'layer1', 'ose3' ]
      mode: destroy
    - role: layer1_rhev
      tags: [ 'layer1', 'rhev' ]
      mode: destroy
    # - role: layer1_vms
    #   tags: [ 'satellite', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: satellite
    # - role: layer1_vms
    #   tags: [ 'rhosp', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: rhosp-all
    - role: layer1_rhosp
      tags: [ 'layer1', 'rhosp' ]
      mode: destroy
      group: rhosp-all
    - role: layer1_dnat
      tags: [ 'layer1', 'dnat' ]
      mode: destroy
    - role: layer1
      tags: [ 'layer1' ]
      mode: destroy
